using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Web.UI;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("CobraResources")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("CobraResources")]
[assembly: AssemblyCopyright("Copyright ©  2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("d9b92fe8-c225-47a1-916a-e459e2b5f2a7")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

[assembly: WebResource("CobraResources.Scripts.Foundation.CobraUIFunctions.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.CobraFoundationScript.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.jquery-3.1.0.min.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.jquery.md5.min.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.Base64.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.Canvas.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.epos-2.9.0.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.epos-interface.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.modernizr.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.moment.min.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.PrinterManager.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.googlemap.interface.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Foundation.jquery.touchSwipe.min.js", "application/x-javascript")]


[assembly: WebResource("CobraResources.Scripts.Widget._System.SubControlCalendar.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.SubControlImageUploader.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.SubControlPopUpInput.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.SubControlSelectionPanel.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.SubControlWidgetGroup.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.SubControlWidgetIcon.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.WidControlCreateUser.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.WidControlImageUploader.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.WidControlLogIn.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.WidControlQRCode.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.WidControlSubscription.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.WidControlUpdateContent.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget._System.WidControlWidgetPanel.js", "application/x-javascript")]

[assembly: WebResource("CobraResources.Scripts.Widget._System._TestComposite.js", "application/x-javascript")]

[assembly: WebResource("CobraResources.Scripts.Widget.GShop_General.WidControlBEAddAdjustItem.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_General.WidControlBEItemList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_General.WidControlBEOrderList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_General.WidControlFEBasicStore.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_General.WidControlFEBasicStoreLocation.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_General.WidControlFEOrderList.js", "application/x-javascript")]

[assembly: WebResource("CobraResources.Scripts.Widget.GShop_Mobile.SubControlMobileStoreFrontGridItem.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_Mobile.SubControlMobileStoreFrontOptionPanel.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_Mobile.SubControlMobileStoreFrontStoreInfo.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_Mobile.WidControlMobileStoreAddAdjustInventory.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_Mobile.WidControlMobileStoreFront.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_Mobile.WidControlMobileStoreInventoryList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_Mobile.WidControlUpdatePriceList.js", "application/x-javascript")]

[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.SubControlPOSItemPanel.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.SubControlPOSKeyPad.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.SubControlPOSPaymentPanel.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.SubControlPOSPopUpReceiptDetail.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.SubControlPOSReceiptOutput.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.SubControlPOSTransactionList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSAddAdjustItem.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSAddAdjustTable.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSAddAdjustUnit.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSAddAdjustUser.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSAppearanceSetting.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSChangePassword.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSControlPanel.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSDailyReceipt.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSDailyStockBalance.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSGeneralSetting.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSItemList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSLanguageSetting.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSLogIn.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSMonthlyTransaction.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSPrinterSetting.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSStaffPermissionSetting.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSQRCode.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSReceiptLayoutSetting.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSReceiptList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSResetPassword.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSStaticCostEditor.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSStaticCostList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSSubscriptionInfo.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSTableList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSTableManager.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSTransaction.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSTransactionSetting.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSUnitList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSUpdateSubscriberInfo.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSUserList.js", "application/x-javascript")]
[assembly: WebResource("CobraResources.Scripts.Widget.GShop_POS.WidControlPOSWidgetRestriction.js", "application/x-javascript")]

[assembly: WebResource("CobraResources.Scripts.ToolBar.ToolBarScript.js", "application/x-javascript")]

[assembly: WebResource("CobraResources.StyleSheets.Foundation.CobraStyle.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Foundation.CobraUIStyle.css", "text/css")]

[assembly: WebResource("CobraResources.StyleSheets.Widget._System.SubControlCalendar.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.SubControlImageUploader.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.SubControlPopUpInput.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.SubControlSelectionPanel.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.SubControlWidgetGroup.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.SubControlWidgetIcon.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.WidControlCreateUser.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.WidControlImageUploader.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.WidControlLogIn.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.WidControlQRCode.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.WidControlSubscription.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.WidControlUpdateContent.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget._System.WidControlWidgetPanel.css", "text/css")]

[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_General.WidControlBEAddAdjustItem.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_General.WidControlBEItemList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_General.WidControlBEOrderList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_General.WidControlFEBasicStore.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_General.WidControlFEBasicStoreLocation.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_General.WidControlFEOrderList.css", "text/css")]

[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_Mobile.SubControlMobileStoreFrontGridItem.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_Mobile.SubControlMobileStoreFrontOptionPanel.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_Mobile.SubControlMobileStoreFrontStoreInfo.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_Mobile.WidControlMobileStoreAddAdjustInventory.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_Mobile.WidControlMobileStoreFront.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_Mobile.WidControlMobileStoreInventoryList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_Mobile.WidControlUpdatePriceList.css", "text/css")]

[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.SubControlPOSItemPanel.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.SubControlPOSKeyPad.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.SubControlPOSPaymentPanel.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.SubControlPOSPopUpReceiptDetail.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.SubControlPOSReceiptOutput.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.SubControlPOSTransactionList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSAddAdjustItem.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSAddAdjustTable.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSAddAdjustUnit.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSAddAdjustUser.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSAppearanceSetting.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSChangePassword.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSControlPanel.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSDailyReceipt.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSDailyStockBalance.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSGeneralSetting.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSItemList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSLanguageSetting.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSLogIn.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSMonthlyTransaction.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSPrinterSetting.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSStaffPermissionSetting.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSQRCode.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSReceiptLayoutSetting.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSReceiptList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSResetPassword.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSStaticCostEditor.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSStaticCostList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSSubscriptionInfo.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSTableList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSTableManager.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSTransaction.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSTransactionSetting.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSUnitList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSUpdateSubscriberInfo.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSUserList.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Widget.GShop_POS.WidControlPOSWidgetRestriction.css", "text/css")]

[assembly: WebResource("CobraResources.StyleSheets.ToolBar.ToolBarStyle.css", "text/css")]

[assembly: WebResource("CobraResources.StyleSheets.Polymorphic.FormUpdateSubscriberInfo.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Polymorphic.FormUpdateUserAccountInfo.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Polymorphic.FormChangePinCode.css", "text/css")]
[assembly: WebResource("CobraResources.StyleSheets.Polymorphic.FormUpdateInstallerSetting.css", "text/css")]

[assembly: WebResource("CobraResources.Icons.Foundation.edit_button.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.list_detail.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.ellipsis_button.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.minus_button.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.plus_button.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.printericon.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.printericon2.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.2upchevron.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.carticon.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.cash.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.upchevron.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.downchevron.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.cross_button.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.tick_button.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.edit_pencil.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.back.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.bin.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.delivered.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.processing.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.shipping.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.refresh.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.rtchevron.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.ltchevron.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.rtchevronplain.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.ellipseorange.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.logout.png", "image/png")]

[assembly: WebResource("CobraResources.Icons.Foundation.1_gray.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.1_green.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.3_gray.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.3_green.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.5_green.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.5_gray.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.icon_envalope.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.icon_process.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.icon_shipping.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.icon_delivered.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.icon_reject.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.openpopup.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.openpopup_gray.png", "image/png")]

[assembly: WebResource("CobraResources.Icons.Foundation.backspace_black.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.backspace_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.cross_black.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.cross_white.png", "image/png")]

[assembly: WebResource("CobraResources.Icons.Foundation.downarrow_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.recycle_bin.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.recycle_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.save_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.bottomarrow_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.toparrow_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.uparrow_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.enter_white.png", "image/png")]
[assembly: WebResource("CobraResources.Icons.Foundation.goto_white.png", "image/png")]

[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Arrows.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_BarCircle.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Bert.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_BertRound.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_BigCircleBall.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_BigRoller.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_BigSnake.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_BouncingBall.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_CircleBall.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_CircleThickBox.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Clock.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_CyclyingBall.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_DarkBar.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_DripCircle.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_ExpandingCircle.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_FaceBook.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Flower.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_FlowerBig.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Hypnotize.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Indicator.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_IndicatorBig.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_IndicatorBigCircle.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_IndicatorLite.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Kit.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_LightBar.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_PacMan.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Pik.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Pk.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Radar.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Refresh.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Roller.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Rotation.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_ShortBar.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_SmallWait.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Snake.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_SquareCircle.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Squares.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_Wheel.gif", "image/gif")]
[assembly: WebResource("CobraResources.Images.AjaxLoader.AJAX_WheelThrobber.gif", "image/gif")]

[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Cart.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Girl.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Home.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Order.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Location.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Man.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Person.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Setting.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Edit.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Recycle.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Add.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_ChangePIN.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_EditUserInfo.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_GeoLocation.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_ShopOwner.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Customers.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_AndriodBackEnd.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_AndriodFrontEnd.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_AndriodLogo.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_iOSBackEnd.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_iOSFrontEnd.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_iOSLogo.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_QRCode.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddCategory.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddItem.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddService.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddStaticCost.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddStaticItem.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddTable.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddTableGroup.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSEditItem.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddBaseUnit.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSAddUnit.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSEditUnit.png", "image/png")]

[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSPurchase.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSSale.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSStockIn.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_POSStockOut.png", "image/png")]

[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Printer.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_PrinterConnection.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_ResetSetting.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_RevertSetting.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_Save.png", "image/png")]

[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_UserListAddUser.png", "image/png")]
[assembly: WebResource("CobraResources.Images.ToolBar.ToolBar_UserListEditUser.png", "image/png")]

[assembly: WebResource("CobraResources.Images.System.NoImage.png", "image/png")]
[assembly: WebResource("CobraResources.Images.System.NoPhoneImage.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.System.NoPhoto01.png", "image/png")]
[assembly: WebResource("CobraResources.Images.System.NoPhoto02.png", "image/png")]
[assembly: WebResource("CobraResources.Images.System.dash.png", "image/png")]
[assembly: WebResource("CobraResources.Images.System.Error.png", "image/png")]

[assembly: WebResource("CobraResources.Images.Widget.Setting_Appearance.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_General.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_Language.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_Printer.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_ReceiptLayout.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_StaffPermission.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_Transaction.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_User.png", "image/png")]
[assembly: WebResource("CobraResources.Images.Widget.Setting_Widget.png", "image/png")]

[assembly: WebResource("CobraResources.Images.Language.CNFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.IDFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.JPFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.KRFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.MMFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.MYFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.THFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.UKFlag.jpg", "image/jpg")]
[assembly: WebResource("CobraResources.Images.Language.VNFlag.jpg", "image/jpg")]