//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobra {
    
    
    public partial class Default {
        
        /// <summary>
        /// CompositeForm1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CobraWebControls.CompositeForm CompositeForm1;
        
        /// <summary>
        /// CompositeAjaxLoaderPopUp1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CobraWebControls.CompositeAjaxLoaderPopUp CompositeAjaxLoaderPopUp1;
        
        /// <summary>
        /// CompositeMessageBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CobraWebControls.CompositeMessageBox CompositeMessageBox1;
    }
}
